# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
#  config.vm.box_url = "http://files.vagrantup.com/precise64.box"	
#  config.vm.box = "precise64"
  config.vm.box = "puppetlabs/ubuntu-16.04-64-nocm"
  config.vm.hostname = 'nginx-server'

# puppetlabs/ubuntu-16.04-64-nocm

	# Setting up webserver
	config.vm.define "web" do |web|
		web.vm.hostname = "nginx-server"
		web.vm.box	= "nginx"
		web.vm.network	"private_network", type: "dhcp"
		web.vm.network "forwarded_port", guest: 8000, host: 8000
		web.vm.provision "puppet" do |puppet|
			puppet.manifests_path = "./puppet/manifests"
		        puppet.manifest_file = "default.pp"
			puppet.options = "--verbose"


	end
end
end
