# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  #Boxes are the package format for Vagrant environments. A box can be used by anyone on any platform that Vagrant supports 
  #to bring up an identical working environment.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"	
  config.vm.box = "precise64"
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080
  #Vagrant Shell provisioner allows you to upload and execute a script within the guest machine. 
  #For more information visit https://www.vagrantup.com/docs/provisioning/shell.html
  config.vm.provision "shell", path: "provision.sh"

end
