# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"	
  config.vm.box = "precise64"

	# Setting up webserver
	config.vm.define "web" do |web|
		web.vm.hostname = "webserver"
		web.vm.box	= "apache"
		web.vm.network	"private_network", type: "dhcp"
		web.vm.network "forwarded_port", guest: 80, host: 8080
		web.vm.provision "puppet" do |puppet|
			puppet.manifests_parth = "manifests"
	end
end
end
