# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

	config.vm.define "web" do |web|
		web.vm.network "forwarded_port", guest: 80, host: 8080
		web.vm.hostname = "webserver"
		web.vm.network "private_network", type: "dhcp"
			web.vm.provision "puppet" do |puppet|
				puppet.manifests_path = "manifests"
				puppet.manifest_file = "default.pp"
			end
	end

	config.vm.define "db" do |db|
		db.vm.hostname = "database"
		db.vm.network "private_network", type: "dhcp"
			db.vm.provision "puppet" do |puppet|
				puppet.manifests_path = "manifests"
				puppet.manifest_file = "database.pp"
			end
	end
	
	config.vm.define "log" do |log|
		log.vm.hostname = "logserver"
		log.vm.network "private_network", type: "dhcp"
		log.vm.network "forwarded_port", guest: 80, host: 8081
			log.vm.provision "puppet" do |puppet|
				puppet.manifests_path = "manifests"
				puppet.manifest_file = "default.pp"
			end
	end
end
